-- CreateEnum
CREATE TYPE "AppSettingKey" AS ENUM ('ALLOW_USER_SIGNUP', 'ALLOW_USER_ACCOUNT_DELETION', 'ALLOW_INVITE_CODE_GENERATION', 'SESSION_TIMEOUT_SECONDS', 'VAULT_ALLOW_PASSWORD_CHANGE', 'VAULT_BLOCK_USER_ON_INCORRECT_PASSWORD', 'VAULT_BLOCK_DURATION_SECONDS', 'VAULT_BLOCK_AFTER_ATTEMPTS', 'VAULT_DEFAULT_AUTH_TYPE', 'VAULT_AUTH_ALLOW_PASSWORD', 'VAULT_AUTH_ALLOW_PIN', 'VAULT_PASSWORD_MIN_LENGTH', 'VAULT_PASSWORD_MAX_LENGTH', 'VAULT_PIN_MIN_LENGTH', 'VAULT_PIN_MAX_LENGTH', 'ALLOW_VAULT_DELETION', 'DISABLE_VAULT_SHARING', 'ADMIN_CAN_DELETE_ANY_VAULT', 'ADMIN_CAN_DELETE_ANY_COLLECTION', 'ALLOW_PUBLIC_COLLECTIONS', 'ADMIN_CAN_CHANGE_RESOURCE_OWNER', 'MAX_VAULTS_PER_USER', 'MAX_COLLECTIONS_PER_USER');

-- DropIndex
DROP INDEX "Game_name_trgm_idx";

-- CreateTable
CREATE TABLE "AppSetting" (
    "id" TEXT NOT NULL,
    "key" "AppSettingKey" NOT NULL,
    "value" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserSettings" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "privacyAllowVaultInvites" BOOLEAN NOT NULL DEFAULT true,
    "privacyAllowCollectionInvites" BOOLEAN NOT NULL DEFAULT true,
    "privacyAllowProfileView" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "UserSettings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AppSetting_key_key" ON "AppSetting"("key");

-- CreateIndex
CREATE UNIQUE INDEX "UserSettings_userId_key" ON "UserSettings"("userId");

-- AddForeignKey
ALTER TABLE "UserSettings" ADD CONSTRAINT "UserSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
