apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamepile-ingress
  namespace: gamepile
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - gamepile.example.com
  rules:
    - host: gamepile.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
