apiVersion: batch/v1
kind: Job
metadata:
  name: sql-migrate
  namespace: gamepile
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17-alpine
          envFrom:
            - configMapRef:
                name: gamepile-config
            - secretRef:
                name: gamepile-secrets
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -d "$DATABASE_URL"; do
                echo "Waiting for PostgreSQL..."
                sleep 3
              done
      containers:
        - name: migrate
          image: ghcr.io/thomaskoeppe/gamepile/migrate:latest
          envFrom:
            - configMapRef:
                name: gamepile-config
            - secretRef:
                name: gamepile-secrets
      restartPolicy: OnFailure